# Generated by Django 5.1.5 on 2025-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_alter_foodmakerprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_protien',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_type',
            field=models.CharField(default='Snacks', max_length=100),
        ),
    ]
