# Generated by Django 5.1.5 on 2025-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_alter_foodmakerprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmakerprofile',
            name='specialized_cuisines',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='foodmakerprofile',
            name='website_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
