# Generated by Django 5.1.5 on 2025-02-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_foodmakerprofile_specialized_cuisines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmakerprofile',
            name='preparation_time',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
