# Generated by Django 5.1.5 on 2025-02-15 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0008_foodmakerprofile_preparation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='food_image2',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_image3',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='foodmaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='foodapp.foodmakerprofile'),
        ),
    ]
