# Generated by Django 5.1.5 on 2025-02-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0009_fooditem_food_image2_fooditem_food_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodmakerprofile',
            name='business_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/'),
        ),
        migrations.AddField(
            model_name='foodmakerprofile',
            name='business_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='business_cards/'),
        ),
    ]
