# Generated by Django 5.1.5 on 2025-02-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0010_foodmakerprofile_business_card_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
